//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unik2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int AuditLog_ID { get; set; }
        public string Record_ID { get; set; }
        public string Operation { get; set; }
        public Nullable<System.DateTime> ChangedAt { get; set; }
    }
}
