//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unik2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.Teachers = new HashSet<Teachers>();
        }
    
        public string CategoryName { get; set; }
        public Nullable<int> Salary { get; set; }
        public int Id_category { get; set; }
    
        public virtual ICollection<Teachers> Teachers { get; set; }
    }
}
