//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unik2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cicle
    {
        public Cicle()
        {
            this.Predmet = new HashSet<Predmet>();
        }
    
        public string Cicle1 { get; set; }
        public int Id_cicle { get; set; }
    
        public virtual ICollection<Predmet> Predmet { get; set; }
    }
}
