//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unik2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Load
    {
        public int Id_predmet { get; set; }
        public int Clocks { get; set; }
        public int Id_teacher { get; set; }
        public int Id_load { get; set; }
    
        public virtual Predmet Predmet { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
