//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unik2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Predmet
    {
        public Predmet()
        {
            this.Load = new HashSet<Load>();
        }
    
        public string PredmetName { get; set; }
        public int Id_cycle { get; set; }
        public int Id_predmet { get; set; }
    
        public virtual Cicle Cicle { get; set; }
        public virtual ICollection<Load> Load { get; set; }
    }
}
