//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unik2.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public Teachers()
        {
            this.Load = new HashSet<Load>();
        }
    
        public string Fio { get; set; }
        public int Id_category { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Apartment { get; set; }
        public int Id_teacher { get; set; }
        public Nullable<int> Id_user { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Load> Load { get; set; }
        public virtual Users Users { get; set; }
    }
}
